name: PlanLite
main: com.djrapitops.planlite.PlanLite
version: 1.6.3

commands:
  planlite:
    usage: /<command> <name>
    description: base command
  inspect:
    usage: /planlite inspect <name>
    description: inspect player data
  analyze:
    usage: /planlite analyze
    description: analyze all players' data, add -refresh to refresh analysis.
  reload:
    usage: /planlite reload
    description: reload plugin config
  search:
    usage: /planlite <search terms> -p add -p to make not search playername
    description: search data of multiple players with search terms
  debug:
    usage: /planlite debug
    description: run commands to debug the plugin.
    
softdepend:
- OnTime
- EssentialsX
- Towny
- Vault
- Factions
- SuperbVote
- PlaceholderAPI
- AdvancedAchievements
- PlayerLogger

permissions:
  planlite.?:
    description: Help command
    default: true
  planlite.inspect:
    description: Allows you to check your player data. 
    default: true
  planlite.inspect.other:
    description: Allows you to check other players' player data.
    default: true
  planlite.analyze:
    description: Allows you to check analysed data about all players.
    default: true
  planlite.analyze.refresh:
    description: Allows you to refresh the analyse result with -r argument
    default: op
  planlite.reload:
    description: Allows to reload plugin config
    default: true
  planlite.search:
    description: Allows search
    default: true
  planlite.info:
    description: Allows to view info
    default: true
  planlite.debug:
    description: Allows debug command
    default: op
  planlite.basic:
    children:
      planlite.?: true
      planlite.inspect: true
      planlite.info: true
      planlite.search: true
  planlite.advanced:
    childer:
      planlite.basic: true
      planlite.analyze: true
  planlite.staff:
    children:
      planlite.debug: true
      planlite.advanced: true
      planlite.inspect.other: true
      planlite.analyze.refresh: true
      planlite.reload: true
  planlite.*:
    children:
      planlite.staff: true