Settings:
  Analysis:
    MinutesPlayedUntilConsidiredActive: 10
  Cache:
    AnalysisCache:
      RefreshAnalysisCacheOnEnable: true
    InspectCache:
      ClearFromInspectCacheAfterXMinutes: 3
    DataCache:
      SaveEveryXMinutes: 5
      ClearCacheEveryXSaves: 5
  WebServer:
    Port: 8804
    ShowAlternativeServerIP: false
    AlternativeIP: your.ip.here:%port%
  PlanLite:
    Enabled: true

database:
  type: sqlite
    
      
    