# -----------------------------------------------------
# Plan Bukkit Configuration file
# More information about each setting:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Bukkit-Configuration
# -----------------------------------------------------
Server:
  ServerName: 'Plan'

# -----------------------------------------------------
# More information about Locale
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Localization
# -----------------------------------------------------
Plugin:
  Debug: false
  Locale: default
  WriteNewLocaleFileOnEnable: false
  Bungee-Override:
    StandaloneMode: false
    CopyBungeeConfig: true

# -----------------------------------------------------
# More information about SSL Certificate Settings:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
# -----------------------------------------------------
WebServer:
  Port: 8804
  # InternalIP usually does not need to be changed, only change it if you know what you're doing!
  # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
  InternalIP: 0.0.0.0
  Security:
    SSL-Certificate:
      KeyStorePath: 'SSLCertificate.keystore'
      KeyPass: 'default'
      StorePass: 'default'
      Alias: 'alias'
# -----------------------------------------------------
Database:
  Type: SQLite
  MySQL:
    Host: localhost
    Port: 3306
    User: root
    Password: minecraft
    Database: Plan
# -----------------------------------------------------
Commands:
  AlternativeIP:
    Enabled: false
    Link: your.domain.here:%port%
  Colors:
    Main: '&2'
    Secondary: '&7'
    Highlight: '&f'

Analysis:
  AutoRefreshPeriod: 60
  Active:
    # Minutes a player should play per week to be considered active
    PlaytimeThreshold: 30
    # How many days player should join per week to be considered active
    LoginThreshold: 2
  LogProgress: true
  Export:
    Enabled: false
    ExternalWebServerLinkProtocol: http
    DestinationFolder: 'Analysis Results'
Data:
  Commands:
    LogUnknownCommands: false
    CombineCommandAliases: true
# -----------------------------------------------------
Customization:
  UseServerTime: true
  Display:
    SessionsAsTable: false
    MaxSessions: 50
    MaxPlayers: 2500
    MaxPlayersPlayersPage: 25000
  Formatting:
    DecimalPoints: '#.##'
    TimeAmount:
      Year: '1 year, '
      Years: '%years% years, '
      Month: '1 month, '
      Months: '%months% months, '
      Day: '1d '
      Days: '%days%d '
      Hours: '%hours%h '
      Minutes: '%minutes%m '
      Seconds: '%seconds%s'
      Zero: '0s'
  WorldAliases:
    world: world

# -----------------------------------------------------
# More information about Themes:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Themes
# -----------------------------------------------------
Theme:
  Base: Default
  Font:
    FontStyleSheet: https://fonts.googleapis.com/css?family=Quicksand:300,400
    FontFamily: "'Quicksand', sans-serif"
    Color:
      Dark: Base
      Light: Base
  Colors:
    Main: Base
    Main-Dark: Base
    Secondary: Base
    Secondary-Dark: Base
    Tertiary: Base
    Background: Base
    Table-Light: Base
    Table-Dark: Base
  Graphs:
    PunchCard: Base
    PlayersOnline: Base
    TPS:
      High-Threshold: 18
      Medium-Threshold: 10
      High: Base
      Medium: Base
      Low: Base
    CPU: Base
    RAM: Base
    Chunks: Base
    Entities: Base
    WorldPie: '"#0099C6", "#66AA00", "#316395", "#994499", "#22AA99", "#AAAA11", "#6633CC", "#E67300", "#329262", "#5574A6"'
    GMDrilldown: '"#438c99", "#639A67", "#D8EBB5", "#D9BF77"'
    ActivityPie: '"#228B22", "#A9A9A9", "#808080", "#951800"'
    ServerPreferencePie: '"#0099C6", "#66AA00", "#316395", "#994499", "#22AA99", "#AAAA11", "#6633CC", "#E67300", "#329262", "#5574A6"'
# -----------------------------------------------------
Plugins:
  Factions:
    HideFactions:
      - ExampleFaction
  Towny:
    HideTowns:
      - ExampleTown
