Settings:
  Debug: false
  Locale: default
  UseTextUI: false
  Data:
    GatherLocations: true
    ChatListener: true
    GatherKillData: true
    GamemodeChangeListener: true
    GatherCommandUsage: true
  Analysis:
    LogProgressOnConsole: false
    NotifyWhenFinished: true
    MinutesPlayedUntilConsidiredActive: 10
    RemoveOutliersFromVisualization: true
    Export:
      Enabled: false
      DestinationFolder: 'Analysis Results'
  Cache:
    Processing:
      GetLimit: 5000
      SaveLimit: 2500
      ClearLimit: 2500
    AnalysisCache:
      RefreshAnalysisCacheOnEnable: true
      RefreshEveryXMinutes: -1
    InspectCache:
      ClearFromInspectCacheAfterXMinutes: 5
    DataCache:
      SaveEveryXMinutes: 2
      ClearCacheEveryXSaves: 5
  WebServer:
    Enabled: true
    Port: 8804
    InternalIP: 0.0.0.0
    ShowAlternativeServerIP: false
    AlternativeIP: your.ip.here:%port%
    LinkProtocol: http
    Security:
      DisplayIPsAndUUIDs: true
      AddressSecurityCode: bAkEd

Customization:
  ServerName: 'Plan'
  SmallHeadImagesOnAnalysisPlayerlist: true
  Graphs:
    PlayersOnlineGraph:
      UseMaxPlayersAsScale: true
  Formats:
    TimeAmount:
      Year: '1 year, '
      Years: '%years% years, '
      Day: '1d '
      Days: '%days%d '
      Hours: '%hours%h '
      Minutes: '%minutes%m '
      Seconds: '%seconds%s'
    DecimalPoints: '#.##'
  Colors:
    Commands:
      Main: '&2'
      Secondary: '&7'
      Highlight: '&f'
    HTML:
      UI:
        Main: 348e0f
        MainDark: 267F00
        Secondary: 5cb239
        Tertiary: 89c471
        TertiaryDark: 5da341
      ActivityGraph:
        OnlinePlayers: '1E90FF'
        OnlinePlayersFill: '75BBFF'
        NewPlayers: '228B22'
      GamemodePie:
        Survival: '951800'
        Creative: '01A1DB'
        Adventure: '769316'
        Spectator: '228B22'
      ActivityPie:
        Active: '228B22'
        Banned: '951800'
        Inactive: 'A9A9A9'
        JoinedOnce: '808080'
  DemographicsTriggers:
    Trigger: "i'm, am, im, bin"
    Female: 'female, girl, gurl, woman, gal, mrs, she, miss, feminin, weiblich, mädchen, frau'
    Male: 'male, boy, man, boe, sir, mr, guy, he, männlich, maskulin, junge, mann'
    IgnoreWhen: 'sure, think, with, are, you, din'
  Plugins:
    Enabled:
      AdvancedAchievements: true
      Essentials: true
      Factions: true
      Jobs: true
      McMMO: true
      OnTime: true
      Towny: true
      Vault: true
    Factions:
      HideFactions:
        - ExampleFaction
    Towny:
      HideTowns:
        - ExampleTown

database:
  type: sqlite
  
mysql:
  host: localhost
  port: 3306
  user: root
  password: minecraft
  database: Plan
