Settings:
  Debug: false
  Locale: default
  UseTextUI: false
  Data:
    ChatListener: true
    GatherKillData: true
    GatherCommandUsage: true
  Analysis:
    LogProgressOnConsole: false
    NotifyWhenFinished: true
    MinutesPlayedUntilConsidiredActive: 10
    Export:
      Enabled: false
      DestinationFolder: 'Analysis Results'
  Cache:
    Processing:
      GetLimit: 5000
      SaveLimit: 2500
      ClearLimit: 2500
    AnalysisCache:
      RefreshAnalysisCacheOnEnable: true
      RefreshEveryXMinutes: -1
    InspectCache:
      ClearFromInspectCacheAfterXMinutes: 5
    DataCache:
      SaveEveryXMinutes: 2
      ClearCacheEveryXSaves: 5
  WebServer:
    Enabled: true
    Port: 8804
    InternalIP: 0.0.0.0
    ShowAlternativeServerIP: false
    AlternativeIP: your.ip.here:%port%
    ExternalWebServerLinkProtocol: http
    Security:
      DisplayIPsAndUUIDs: true
      Certificate:
        KeyStorePath: '\SSLCertificate.keystore'
        KeyPass: 'default'
        StorePass: 'default'
        Alias: 'alias'

Customization:
  ServerName: 'Plan'
  SmallHeadImagesOnAnalysisPlayerlist: true
  Data:
    DoNotLogUnknownCommands: false
    CombineCommandAliasesToMainCommand: false
  Formats:
    TimeAmount:
      Year: '1 year, '
      Years: '%years% years, '
      Day: '1d '
      Days: '%days%d '
      Hours: '%hours%h '
      Minutes: '%minutes%m '
      Seconds: '%seconds%s'
    DecimalPoints: '#.##'
  Colors:
    Commands:
      Main: '&2'
      Secondary: '&7'
      Highlight: '&f'
    HTML:
      UI:
        Main: 348e0f
        MainDark: 267F00
        Secondary: 5cb239
        Tertiary: 89c471
        TertiaryDark: 5da341
      ActivityGraph:
        OnlinePlayers: '1E90FF'
        NewPlayers: '228B22'
      GamemodePie:
        Survival: '438c99'
        Creative: '639A67'
        Adventure: 'D8EBB5'
        Spectator: 'D9BF77'
      ActivityPie:
        Active: '228B22'
        Banned: '951800'
        Inactive: 'A9A9A9'
        JoinedOnce: '808080'
  Plugins:
    Factions:
      HideFactions:
        - ExampleFaction
    Towny:
      HideTowns:
        - ExampleTown

database:
  type: sqlite
  
mysql:
  host: localhost
  port: 3306
  user: root
  password: minecraft
  database: Plan
