debug: true

RefreshAnalysisOnEnable: true
saveEveryXMinutes: 5
database:
  type: sqlite

WebServer:
  Port: 8804

enabledData:
  planLite:
    pluginEnabled: true
    
    towny: true
    factions: true
    achievements: true
    votes: true
    economy: true
    essentials:
      ruleBreaking: true
  
  server:
    commandUsage: true
    playersOnline: true
    amountOfNewPlayers: true
    
    
      
    