name: Plan
author: Rsl1122
main: com.djrapitops.plan.Plan
version: 2.0.0

commands:
  plan:
    usage: /<command> <name>
    description: base command
  inspect:
    usage: /plan inspect <name>
    description: inspect player data
  analyze:
    usage: /plan analyze
    description: analyze all players' data, add -refresh to refresh analysis.
  reload:
    usage: /plan reload
    description: reload plugin config
  search:
    usage: /plan <search terms> -p add -p to make not search playername
    description: search data of multiple players with search terms
  debug:
    usage: /plan debug
    description: run commands to debug the plugin.
    
softdepend:
- PlanLite

permissions:
  plan.?:
    description: Help command
    default: true
  plan.inspect:
    description: Allows you to check your player data. 
    default: true
  plan.inspect.other:
    description: Allows you to check other players' player data.
    default: true
  plan.analyze:
    description: Allows you to check analysed data about all players.
    default: true
  plan.analyze.refresh:
    description: Allows you to refresh the analyse result with -r argument
    default: op
  plan.reload:
    description: Allows to reload plugin config
    default: true
  plan.search:
    description: Allows search
    default: true
  plan.info:
    description: Allows to view info
    default: true
  plan.debug:
    description: Allows debug command
    default: op
  
  plan.basic:
    children:
      plan.?: true
      plan.inspect: true
      plan.info: true
      plan.search: true
  plan.advanced:
    childer:
      plan.basic: true
      plan.analyze: true
  plan.staff:
    children:
      plan.debug: true
      plan.advanced: true
      plan.inspect.other: true
      plan.analyze.refresh: true
      plan.reload: true
  plan.*:
    children:
      plan.staff: true