
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd Plan
        ./gradlew build
    - name: SonarCloud
      run: |
        cd Plan
        ./gradlew sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=player-analytics-plan -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=5 -Dsonar.pullrequest.provider=GitHub -Dsonar.pullrequest.github.repository=plan-player-analytics/Plan
